services:
  db:
    hostname: db
    container_name: postgres-databases
    image: postgres:15
    shm_size: 128mb
    env_file:
      - .docker/.env.development
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - bank-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ms-customers-dev:
    container_name: ms-customers-dev
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    command: mvn -pl ms-customers spring-boot:run
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bank-net

  ms-accounts-dev:
    container_name: ms-accounts-dev
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    command: mvn -pl ms-accounts spring-boot:run
    ports:
      - 8082:8082
    depends_on:
      db:
        condition: service_healthy
      ms-customers-dev:
        condition: service_started
    networks:
      - bank-net

  adminer:
    hostname: adminer
    container_name: adminer-bank-system
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - bank-net

  dozzle:
    hostname: dozzle
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_ADDR=:9999
      - DOZZLE_ENABLE_ACTIONS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:9999
    networks:
      - bank-net

  ms-customers:
    build: ./ms-customers
    container_name: ms-customers
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customers_db
      - POSTGRES_HOST=db
      - POSTGRES_DB_CUSTOMERS=customers_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - bank-net

  ms-accounts:
    build: ./ms-accounts
    container_name: ms-accounts
    ports:
      - 8082:8082
    depends_on:
      db:
        condition: service_healthy
      ms-customers:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/accounts_db
      - POSTGRES_HOST=db
      - POSTGRES_DB_ACCOUNTS=accounts_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - CUSTOMERS_SERVICE_URL=http://ms-customers:8081
    networks:
      - bank-net

volumes:
  pg_data:


networks:
  bank-net:
